receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"
processors:
  batch:
    timeout: 1000ms

exporters:
  debug:
    verbosity: detailed
  otlp/tempo:
    endpoint: tempo:4317 # Forward traces to Tempo's gRPC OTLP endpoint
    tls:
      insecure: true
  prometheus:
    endpoint: 0.0.0.0:8889 # Expose metrics for Prometheus to scrape
extensions:
  health_check: {}

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, prometheus] # Receive OTLP metrics and expose for Prometheus
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp/tempo] # Receive OTLP traces and forward to Tempo
