global:
  scrape_interval: 15s # How frequently to scrape targets
  evaluation_interval: 15s # How frequently to evaluate rules

scrape_configs:
  - job_name: 'prometheus' # Scrape Prometheus itself
    static_configs:
      - targets: ['localhost:9090'] # Prometheus's own metrics endpoint

  - job_name: 'otel-collector' # Scrape OpenTelemetry Collector's internal metrics
    static_configs:
      - targets: ['otel-collector:8888'] # OTel Collector metrics endpoints
      - targets: ['otel-collector:8889']
