server:
  http_listen_port: 9080
  grpc_listen_port: 0
positions:
  filename: /tmp/positions.yaml # Stores read positions to prevent reprocessing
clients:
  - url: http://loki:3100/loki/api/v1/push # Loki's push API endpoint
scrape_configs:
  - job_name: docker # Define a scraping job for Docker containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock # Use Docker socket for service discovery
        refresh_interval: 5s # How often Promtail checks Docker for new containers
    relabel_configs:
      - source_labels: ['__meta_docker_container_name'] # Get container name
        regex: '/(.*)'
        target_label: 'container' # Assign container name to 'container' label
      - source_labels: ['__meta_docker_container_id']
        regex: '(.*)'
        target_label: 'instance' # Assign container ID to 'instance' label
